apiVersion: apps/v1
kind: Deployment
metadata:
  name: okhihi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okhihi
  template:
    metadata:
      labels:
        app: okhihi
    spec:
      containers:
      - image: okteto.dev/okhihi:latest
        name: okhihi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "319089ba-8021-4591-8fd4-e83588a2a0b3"
        - name: Vless_Path
          value: "/uhiuogbk"
        - name: Vmess_UUID
          value: "319089ba-8021-4591-8fd4-e83588a2a0b3"
        - name: Vmess_Path
          value: "/nufudtssv"
        - name: Share_Path
          value: "/v2link"
